name: Release

on: [push]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test
        run: go test ./...
      - name: Build
        run: go build -o gpg-bridge.exe .
      - name: Upload portable executable
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: gpg-bridge.exe
